title: Atul Singh Notes
description: Explore the long-form research and book projects stored in this repository.
markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
repository: atulsingh-nikki/obsidian-notes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
github:
  is_project_page: false
