title: Atul Singh Notes
description: Explore the long-form research and book projects stored in this repository.
markdown: kramdown
kramdown:
  input: GFM
  math_engine: null
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
repository: atulsingh-nikki/obsidian-notes
url: "https://atulsingh-nikki.github.io"
baseurl: "/obsidian-notes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
github:
  is_project_page: false
future: true

# Configure Google Analytics by setting a measurement ID.
# Update this value to change the property that receives traffic metrics.
google_analytics: G-3X6LQQ24YV
